// A small built-in text: ten of Aesop's fables (public-domain stories),
// retold in plain words for this page. About 1,300 words in total.
export const FABLES = `
The Fox and the Grapes. One hot day a hungry fox walked into a garden. He saw a bunch of ripe grapes hanging high on a vine. The fox jumped up, but he could not reach the grapes. He jumped again and again, but the grapes were too high. At last the fox gave up and walked away. As he went, he said, "Those grapes are sour anyway. I did not want them." It is easy to hate what you cannot have.

The Tortoise and the Hare. A hare laughed at a tortoise because the tortoise was so slow. "Let us have a race," said the tortoise, "and we will see who is slow." The hare laughed again and agreed. The race began, and the hare ran far ahead. Soon the hare was so far ahead that he lay down under a tree to sleep. The tortoise kept walking, slow and steady. When the hare woke up, he ran as fast as he could, but it was too late. The tortoise had already won the race. Slow and steady wins the race.

The Lion and the Mouse. A lion was sleeping in the forest when a little mouse ran over his face. The lion woke up and caught the mouse in his paw. "Please let me go," said the mouse, "and one day I will help you." The lion laughed, because he did not think a little mouse could help a lion. But he let the mouse go. A few days later the lion was caught in a hunter's net. He roared and roared, but he could not get free. The little mouse heard the lion and ran to him. The mouse chewed the ropes of the net until the lion was free. "You laughed at me," said the mouse, "but now you see that a little mouse can help a lion." Little friends may prove great friends.

The Crow and the Pitcher. A thirsty crow found a pitcher with a little water at the bottom. The crow put his beak into the pitcher, but he could not reach the water. He tried to push the pitcher over, but it was too heavy. Then the crow had an idea. He picked up a small stone and dropped it into the pitcher. Then he dropped another stone, and another, and another. With every stone the water rose a little higher. At last the water was high enough, and the crow drank until he was no longer thirsty. Little by little does the trick.

The Boy Who Cried Wolf. A young boy watched the sheep near a village. He was bored, so he cried out, "Wolf! Wolf! A wolf is chasing the sheep!" The people of the village ran up the hill to help the boy, but there was no wolf. The boy laughed at them. A few days later he cried out again, "Wolf! Wolf!" Again the people ran up the hill, and again there was no wolf. Then one evening a real wolf came out of the forest. The boy cried out, "Wolf! Wolf! A wolf is chasing the sheep!" But this time the people did not come, because they did not believe him. The wolf ate many of the sheep. Nobody believes a liar, even when he tells the truth.

The Ant and the Grasshopper. All summer long a grasshopper sang and played in the sun. An ant walked past him every day, carrying food to her nest. "Why do you work so hard?" asked the grasshopper. "Come and sing with me." "I am storing food for the winter," said the ant, "and you should do the same." The grasshopper laughed and kept singing. When winter came, the grasshopper had no food and he was very hungry. He went to the ant and asked for something to eat. "You sang all summer," said the ant, "so now you can dance all winter." It is wise to prepare today for the needs of tomorrow.

The Fox and the Crow. A crow found a piece of cheese and flew up into a tree to eat it. A fox saw the crow and wanted the cheese. "Good morning, beautiful bird," said the fox. "Your feathers are so bright and your eyes are so clear. I am sure your voice is the most beautiful of all. Will you sing for me?" The crow was pleased, and she opened her beak to sing. The cheese fell to the ground, and the fox caught it. "Thank you," said the fox, "and next time, do not trust a flatterer." Do not trust a flatterer.

The Wind and the Sun. The wind and the sun had an argument about who was stronger. They saw a man walking along the road in a warm coat. "Let us see who can take the coat off the man," said the sun. The wind went first. He blew and blew as hard as he could, but the harder the wind blew, the tighter the man held his coat. At last the wind gave up. Then the sun came out and shone on the man. The man grew warm, and soon he was so hot that he took off his coat. The sun had won. Kindness works better than force.

The Dog and His Reflection. A dog found a bone and carried it home in his mouth. On the way he crossed a bridge over a river. The dog looked down into the water and saw another dog with a bigger bone. He did not know that it was only his own reflection. The dog wanted the bigger bone, so he opened his mouth to bark at the other dog. His own bone fell into the river and was gone. The greedy dog went home with nothing. If you want too much, you may lose what you have.

The Town Mouse and the Country Mouse. A country mouse invited her friend the town mouse to dinner. The country mouse gave her friend beans, bread and cheese. The town mouse laughed at the simple food. "Come to the town with me," she said, "and I will show you how to live." So the two mice went to the town. In a great house they found cake, honey and fruit on the table. But just as they began to eat, a cat ran into the room. The two mice ran and hid in a hole. When the cat had gone, they came out again, but then a dog came in barking. The country mouse said, "Goodbye, my friend. I would rather eat beans in peace than cake in fear." A simple life in peace is better than a rich life in fear.
`;
